# Basic dockerized environment for building and using BinaryRTS
# Taken from: https://github.com/JetBrains/clion-remote/blob/master/Dockerfile.cpp-env-ubuntu
FROM ubuntu:20.04

RUN DEBIAN_FRONTEND="noninteractive" apt-get update && apt-get -y install tzdata

RUN apt-get update \
  && apt-get install -y build-essential \
      gcc \
      g++ \
      gdb \
      clang \
      make \
      ninja-build \
      cmake \
      autoconf \
      automake \
      libtool \
      valgrind \
      locales-all \
      dos2unix \
      rsync \
      tar \
      python3 \
      python3-dev \
      python3-distutils \
      python3-pip \
      python3-docutils \
      curl \
      git \
      pkg-config \
      libseccomp-dev \
      libjansson-dev \
      libyaml-dev \
      libxml2-dev \
      cscope \
  && apt-get clean

# Install poetry (used to build CLI project)
RUN curl -sSL https://install.python-poetry.org | python3 -

# Install ctags
RUN git clone https://github.com/universal-ctags/ctags.git
RUN cd ctags && ./autogen.sh && ./configure && make && make install
