# Basic dockerized environment for building and using BinaryRTS
# Taken from: https://github.com/JetBrains/clion-remote/blob/master/Dockerfile.cpp-env-ubuntu
FROM ubuntu:20.04

ENV DEBIAN_FRONTEND="noninteractive"
ENV PATH="${PATH}:/root/.local/bin/"

WORKDIR /

RUN apt-get update -qq \
  && apt-get install -qq -y tzdata \
  && apt-get install -qq -y \
      autoconf \
      automake \
      build-essential \
      clang \
      cmake \
      cscope \
      curl \
      dos2unix \
      g++ \
      gcc \
      gdb \
      git \
      libjansson-dev \
      libseccomp-dev \
      libtool \
      libxml2-dev \
      libyaml-dev \
      locales-all \
      make \
      ninja-build \
      pkg-config \
      python3 \
      python3-dev \
      python3-distutils \
      python3-docutils \
      python3-pip \
      rsync \
      tar \
      valgrind \
      wget \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && wget -O install.py -q https://install.python-poetry.org \
  && python3 install.py --version 1.2.1 \
  && poetry --version \ 
  && rm install.py \ 
  && git clone https://github.com/universal-ctags/ctags.git 

# Install ctags
WORKDIR /ctags

RUN ./autogen.sh \ 
  && ./configure \
  && make \
  && make install

WORKDIR /
